[package]
name = "crdf"
version = "0.1.0"
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/crdf/"
description = "A CRDT-based RDF graph implementation in Rust, built on top of crdt-graph."
edition.workspace = true

[dependencies]
crdt-graph = { path = "../../crdt-graph", version = "0.3.1" }
uuid = { version = "1.23.1", features = ["v7"] }
thiserror = "2.0.18"
oxrdf = "0.3.3"

[dev-dependencies]
